name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      LOCAL: abel-firvida.ddns.net
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build site
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ./public/
          remote: /var/www/abel-firvida
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          rmRemote: true
          dotfiles: true